sonar.host.url=https://sonarcloud.io
sonar.organization=lopezzuluagaj3-collab
sonar.projectKey=lopezzuluagaj3-collab_sirius-pipeline-tlc
sonar.projectName=sirius-pipeline-tlc
sonar.sources=.
sonar.qualitygate.wait=true

# Ignora directorios de ejecucion local de Terraform
sonar.exclusions=**/.terraform/**, **/.terraform.lock.hcl
